# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 贵州黔行 - 走遍贵州88县市，发现黔地之美
subtitle: '贵州旅游全攻略'
description: '贵州黔行是一个专注贵州全域旅游的推广网站，覆盖贵阳、安顺、遵义、毕节等88个县市的美食、景点、人文与出行攻略。走遍大地神州，醉美多彩贵州。'
keywords: '贵州旅游,贵州美食,贵州景点,黄果树瀑布,甲秀楼,安顺,贵阳,遵义,毕节,黔东南,贵州攻略,贵州自由行,贵州自驾游,贵州避暑,少数民族文化,苗族,侗族'
author: 山间听雨者
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://guizhouren.netlify.app
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - 'sw.js'
  - 'manifest.json'

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
include:
exclude:
ignore:

# Extensions
theme: butterfly

# Deployment
deploy:
  type: ''

# ---------------
# SEO Settings
# ---------------

# Sitemap (for Google / Bing)
sitemap:
  path:
    - sitemap.xml
    - baidusitemap.xml
  rel: false
  tags: true
  categories: true

# Baidu Sitemap (for Baidu)
baidusitemap:
  path: baidusitemap.xml

# RSS Feed (for content syndication)
feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 30
  hub:
  content: true
  content_limit: 500
  content_limit_delim: ''
